FROM python:3.9                     
WORKDIR /django-api     

ENV PYTHONUNBUFFERD 1                       

COPY ./requirements.txt /requirements.txt   
RUN pip install -r /requirements.txt        

                    
                       
             
